# Generated by Django 3.2.16 on 2023-01-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipRead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='QuesModel',
        ),
    ]
