# Generated by Django 3.2.16 on 2023-01-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LipRead', '0002_auto_20230117_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_num', models.IntegerField()),
                ('selected_answer', models.CharField(max_length=500)),
            ],
        ),
    ]
